infinite_import_list:
    pattern: /
    defaults:
        _controller: infinite_import.controller.import:listAction

infinite_import_view:
    pattern: /{id}
    defaults:
        _controller: infinite_import.controller.import:viewAction
    requirements:
        id: \d+

infinite_import_start:
    pattern: /{id}/start
    defaults:
        _controller: infinite_import.controller.import:startAction
    requirements:
        _method: POST
