infinite_import_list:
    path: /
    defaults:
        _controller: infinite_import.controller.import:listAction

infinite_import_view:
    path: /{id}
    defaults:
        _controller: infinite_import.controller.import:viewAction
    requirements:
        id: \d+

infinite_import_start:
    path: /{id}/start
    defaults:
        _controller: infinite_import.controller.import:startAction
    requirements:
        methods: POST
