infinite_import_process_start:
    pattern: /process/{id}
    defaults:
        _controller: infinite_import.controller.process:startAction

infinite_import_process_process:
    pattern: /process/{id}/{processor}
    defaults:
        _controller: infinite_import.controller.process:processAction

infinite_import_process_list:
    pattern: /process
    defaults:
        _controller: infinite_import.controller.process:listAction
